Added Copyright template - COPYRIGHT.md
zendframework/maintainers pull request #44
Opened 2018-03-29 08:42 UTC by webimpress

As it was agreed a long time ago .... we need COPYRIGHT.md file and then in headers we are going to have reference to that file.

As I'm updating zend-coding-standard we need template in one common place.

2018-04-04 21:09 UTC, weierophinney requested changes

2018-04-04 21:09 UTC, weierophinney commented on COPYRIGHT.md
> +Copyright (c) 2015-2018, Zend Technologies USA, Inc.
Needs the following line after it:

```text
All rights reserved.
```

The start year on this one should probably be 2005, as it references the project, and not necessarily the repository.

2018-04-04 21:09 UTC, weierophinney commented on LICENSE.md
>  All rights reserved.
Sucks that we have to repeat it here, but that's how the BSD license is phrased. So we'll have it in two locations, essentially.

2018-04-04 21:09 UTC, weierophinney commented on bin/zf-maintainer
> + * @copyright https://github.com/zendframework/maintainers/blob/master/COPYRIGHT.md Copyright
Here and all others referencing the repo's copyright file: we do not need the word "Copyright" at the end; it's already in the annotation name.

2018-04-04 21:09 UTC, weierophinney commented on template/COPYRIGHT.md
> +Copyright (c) {year}, Zend Technologies USA, Inc.
Needs the following line after it:

```text
All rights reserved.
```

2018-04-09 07:29 UTC, webimpress commented on COPYRIGHT.md
> +Copyright (c) 2005-2018, Zend Technologies USA, Inc. All rights reserved.
@weierophinney Do we need to add here also link to www.zend.com?

Current copyright tag description is:
`Copyright (c) 2005-2017 Zend Technologies USA Inc. (https://www.zend.com)`.

2018-04-09 14:25 UTC, webimpress commented on COPYRIGHT.md
> +Copyright (c) 2005-2018, Zend Technologies USA, Inc. All rights reserved.
@weierophinney It's updated now.

2019-12-31 19:42 UTC, closed without merging